[workspace]
members = ["runtime"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "Apache-2.0 WITH LLVM-exception"

[package]
name = "pumpc"
description = "The Pump compiler: frontend, Cranelift backend, JIT and linker driver."
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "pump"
path = "src/main.rs"

[lib]
name = "pumpc"
path = "src/lib.rs"

[dependencies]
pump-runtime = { path = "runtime" }

cranelift-codegen = "=0.126.0"
cranelift-frontend = "=0.126.0"
cranelift-module = "=0.126.0"
cranelift-jit = "=0.126.0"
cranelift-object = "=0.126.0"
target-lexicon = "0.13"

[profile.release]
panic = "abort"
